### ISSUE TITLE
这个主题非常棒！可以把左上图标右边的昵称长度放大些吗？

### ISSUE THREAD

**Issue by dosedo** [erlzhang/jekyll-theme-persephone#10]
非常好的主题，谢谢作者！！   如标题所说，因为我的昵称过长，出现了换行，朋友可以帮我把昵称的宽度 放大一点吗？请参考下图

<img width="350" alt="image" src="https://user-images.githubusercontent.com/37354346/95649959-2a7c3780-0b13-11eb-878e-a1dd8bbdccb8.png">

**Comment by erlzhang** [comment]
这个css动画效果所限制宽度不能做到自适应，可以在`_config.yml`中添加个自定义样式

```yml
head_code: |
  <style>
    .logo img+h1 {
        width: 200px!important;
    }
  </style>
```
