### ISSUE TITLE
【Feature Request】能否增加 TOC 功能

### ISSUE THREAD

**Issue by simowce** [erlzhang/jekyll-theme-persephone#7]
Hi：

首先，这个主题我真的真的非常非常的喜欢，真的是太好看了，而且是我最喜欢的简约风格，就是我理想中的博客主题。

但是呢，我自己的博客跟代码相关性比较多，会有很多的一级标题二级标题等，如果有一个 侧边 TOC 的话，就更好了。

我尝试自己实现了一下，但是感觉都是在破坏这个主题的美感。

因此能否请作者大大加一个 TOC 的选项呢？

再次感谢您的这个主题。

**Comment by erlzhang** [comment]
可以的，很早就有过这个想法，预计下一个版本会实现

**Comment by erlzhang** [comment]
主题的0.2.5版本已发布，已支持 `jekyll-toc` 插件，需要手动安装，可参考我博客的[Gemfile](https://github.com/erlzhang/erl.im/blob/master/Gemfile#L26)和[_config.yml](https://github.com/erlzhang/erl.im/blob/master/_config.yml#L72)配置。

[效果预览](https://erl.im/blog/learning-method-from-education-psychology.html)

**Comment by simowce** [comment]
> 主题的0.2.5版本已发布，已支持 `jekyll-toc` 插件，需要手动安装，可参考我博客的[Gemfile](https://github.com/erlzhang/erl.im/blob/master/Gemfile#L26)和[_config.yml](https://github.com/erlzhang/erl.im/blob/master/_config.yml#L72)配置。
> 
> [效果预览](https://erl.im/blog/learning-method-from-education-psychology.html)

谢谢您，效果真的是太优雅了。

**Comment by simowce** [comment]
Hi, 我创建了一个博客，已经按照您的设置在 Gemfile 加上了：
```
gem "jekyll-theme-persephone"
gem "jekyll-toc"
```
也在 `_config.yml` 里面把主题设置为了 theme: jekyll-theme-persephone，以及加上了：

```
plugins:
  - jekyll-feed
  - jekyll-toc
```

但是在有目录的文章依旧没有侧边 TOC 出现，不知道是什么原因呢？
